export const constelacionNosotrosConfig = {
  id: 'constelacion-nosotros',
  name: 'Constelación de Nosotros',
  fields: [
    {
      name: 'nombre_constelacion',
      label: 'Nombre de la constelación',
      type: 'text',
      placeholder: 'Ej. Ana & Leo',
      defaultValue: 'Nuestra Constelación',
      maxLength: 40,
    },
    {
      name: 'pareja_a',
      label: 'Nombre 1',
      type: 'text',
      placeholder: 'Ej. Ana',
      maxLength: 24,
    },
    {
      name: 'pareja_b',
      label: 'Nombre 2',
      type: 'text',
      placeholder: 'Ej. Leo',
      maxLength: 24,
    },
    {
      name: 'fecha_inicio',
      label: 'Fecha que nos conocimos',
      type: 'text',
      placeholder: 'Ej. 14 / 02 / 2020',
      maxLength: 20,
    },
    {
      name: 'fotos',
      label: 'Tus fotos (mínimo 3, máximo 8)',
      type: 'file',
      multiple: true,
      accept: 'image/*',
      maxFiles: 8,
    },
    {
      name: 'fechas',
      label: 'Fecha de cada foto (una por línea, en el mismo orden)',
      type: 'textarea',
      placeholder: 'Primer beso — 14/02/2020\nPrimer viaje — 21/06/2020\n...',
      maxLength: 600,
    },
    {
      name: 'mensaje_final',
      label: 'Mensaje del registro estelar',
      type: 'textarea',
      placeholder: 'Ej. Nuestra historia escrita en las estrellas...',
      maxLength: 240,
    },
    {
      name: 'tema',
      label: 'Tema del cielo',
      type: 'select',
      options: [
        { value: 'cosmos',    label: 'Cosmos — azul profundo y estrellas blancas' },
        { value: 'romantica', label: 'Romántica — magenta y rosas' },
        { value: 'dorada',    label: 'Dorada — ámbar y oro antiguo' },
        { value: 'esmeralda', label: 'Esmeralda — verde profundo' },
      ],
      defaultValue: 'cosmos',
    },
    {
      name: 'musica',
      label: 'Música de fondo (Opcional)',
      type: 'file',
      accept: 'audio/*',
      required: false,
    },
  ],
};
